"""Checklist item — actionable task generated by rules engine or admin actions."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class ChecklistItem(TimestampMixin, Base):
    __tablename__ = "checklist_items"
    __table_args__ = (
        Index("ix_checklist_items_case_id", "case_id"),
    )

    case_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cases.id"), nullable=False
    )
    type: Mapped[str] = mapped_column(
        String(50), nullable=False
    )
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="open"
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    related_field_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("extracted_fields.id"),
        nullable=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    case: Mapped[Case] = relationship(foreign_keys=[case_id])
    related_field: Mapped[ExtractedField | None] = relationship(
        foreign_keys=[related_field_id]
    )


# Deferred imports to avoid circular dependency
from app.models.case import Case  # noqa: E402, F811
from app.models.extracted_field import ExtractedField  # noqa: E402, F811
