"""Abstract base for validation rules."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass
class RuleResult:
    """Output of a single rule evaluation."""

    rule_key: str
    severity: str  # low | medium | high
    status: str  # pass | fail | warn
    message: str  # Turkish user-facing message
    related_field_ids: list[str] = field(default_factory=list)


@dataclass
class ChecklistEntry:
    """A checklist item generated by a rule."""

    type: str
    # missing_field | missing_document | conflict_detected |
    # expired_document | composition_error
    severity: str  # low | medium | high
    title: str  # Turkish
    description: str  # Turkish
    related_field_id: str | None = None  # UUID string, nullable


@dataclass
class RuleOutput:
    """Combined output of a rule run."""

    results: list[RuleResult] = field(default_factory=list)
    checklist_entries: list[ChecklistEntry] = field(
        default_factory=list
    )


class BaseRule(ABC):
    """Abstract base for all validation rules."""

    @abstractmethod
    def evaluate(
        self,
        case_id: str,
        fields: list,
        documents: list,
    ) -> RuleOutput:
        """
        Evaluate rule against case data.

        Args:
            case_id: UUID string of the case.
            fields: List of ExtractedField ORM objects for this case.
            documents: List of Document ORM objects for this case.

        Returns:
            RuleOutput with results and checklist entries.
        """
        ...
