"""Rules engine — runs all validation rules against a case."""

from __future__ import annotations

import json
import logging
import uuid

from sqlalchemy.orm import Session

from app.models.case import Case
from app.models.checklist_item import ChecklistItem
from app.models.document import Document
from app.models.extracted_field import ExtractedField
from app.models.validation_result import ValidationResult
from app.services.audit import write_audit
from app.services.rules.base import RuleOutput
from app.services.rules.certificate import CertificateValidity
from app.services.rules.composition import CompositionSum100
from app.services.rules.conflicts import ConflictDetection
from app.services.rules.missing_docs import MissingCriticalDocs
from app.services.rules.quantity import QtyMismatch

logger = logging.getLogger(__name__)

# All rules in evaluation order
ALL_RULES = [
    MissingCriticalDocs(),
    CompositionSum100(),
    CertificateValidity(),
    QtyMismatch(),
    ConflictDetection(),
]

# Types generated by the engine (used for idempotent cleanup)
ENGINE_GENERATED_TYPES = {
    "missing_field",
    "missing_document",
    "conflict_detected",
    "expired_document",
    "composition_error",
}


class RulesEngine:
    """Orchestrates rule evaluation for a case."""

    @staticmethod
    def run_all(
        db: Session,
        case: Case,
        actor_id: uuid.UUID,
    ) -> dict:
        """
        Run all validation rules against a case.

        Idempotent: deletes previous results before re-running.
        Returns summary dict with counts and totals.
        """
        # Fetch data
        fields = (
            db.query(ExtractedField)
            .filter(ExtractedField.case_id == case.id)
            .all()
        )
        documents = (
            db.query(Document)
            .filter(Document.case_id == case.id)
            .all()
        )

        # Clear previous results for idempotent re-runs
        db.query(ValidationResult).filter(
            ValidationResult.case_id == case.id
        ).delete()
        db.query(ChecklistItem).filter(
            ChecklistItem.case_id == case.id,
            ChecklistItem.type.in_(ENGINE_GENERATED_TYPES),
        ).delete(synchronize_session="fetch")
        db.flush()

        # Run rules
        all_results = []
        all_checklist = []
        for rule in ALL_RULES:
            try:
                output: RuleOutput = rule.evaluate(
                    str(case.id), fields, documents
                )
                all_results.extend(output.results)
                all_checklist.extend(output.checklist_entries)
            except Exception as exc:
                logger.error(
                    "Rule %s failed for case %s: %s",
                    rule.__class__.__name__,
                    case.id,
                    exc,
                )

        # Persist ValidationResult rows
        for r in all_results:
            vr = ValidationResult(
                case_id=case.id,
                rule_key=r.rule_key,
                severity=r.severity,
                status=r.status,
                message=r.message,
                related_field_ids=(
                    json.dumps(r.related_field_ids)
                    if r.related_field_ids
                    else None
                ),
            )
            db.add(vr)

        # Persist ChecklistItem rows
        for entry in all_checklist:
            ci = ChecklistItem(
                case_id=case.id,
                type=entry.type,
                severity=entry.severity,
                status="open",
                title=entry.title,
                description=entry.description,
                related_field_id=(
                    uuid.UUID(entry.related_field_id)
                    if entry.related_field_id
                    else None
                ),
            )
            db.add(ci)

        # Audit
        passed = sum(1 for r in all_results if r.status == "pass")
        failed = sum(1 for r in all_results if r.status == "fail")
        warnings = sum(
            1 for r in all_results if r.status == "warn"
        )

        write_audit(
            db,
            actor_id,
            "case.validation_completed",
            "case",
            case.id,
            {
                "total_rules": len(all_results),
                "passed": passed,
                "failed": failed,
                "warnings": warnings,
                "checklist_items_created": len(all_checklist),
            },
        )

        db.commit()

        return {
            "case_id": case.id,
            "total_rules": len(all_results),
            "passed": passed,
            "failed": failed,
            "warnings": warnings,
            "checklist_items_created": len(all_checklist),
        }
